### ISSUE TITLE
Upgrade to .Net Standard 2.0

### ISSUE THREAD

**Issue by balbarak** [omar/ByteSize#34]
Useful library, kindly migrate to Net Standard 2.0 to reduce the dependencies with the library

**Comment by omar** [comment]
The support for .NET Standard 2.0 should be transparent, that is, since it supports netstandard 1.6, it automatically supports netstandard 2.0. The additional dependencies you're seeing only apply when targeting netstandard 1.6, if your project is netstandard 2.0, no additional dependencies should be pulled in.

If more dependencies are being pulled in, can you show where that's happening?

**Comment by omar** [comment]
Version 2 will only support .NET Standard 2.0, see alpha version here https://www.nuget.org/packages/ByteSize/2.0.0-alpha1 and PR #24
